/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "secondary-container": "#474746",
        "primary-container": "#0a0a0a",
        "on-secondary-container": "#b7b5b4",
        "on-tertiary-fixed-variant": "#004493",
        "tertiary-fixed-dim": "#adc7ff",
        "tertiary-container": "#00091f",
        "surface-dim": "#141313",
        "inverse-primary": "#5f5e5e",
        "on-error": "#690005",
        "surface-container-lowest": "#0e0e0e",
        "background": "#141313",
        "primary-fixed": "#e5e2e1",
        "error": "#ffb4ab",
        "outline": "#8e9192",
        "on-primary-container": "#7b7979",
        "on-tertiary": "#002e68",
        "on-primary": "#313030",
        "surface-container-high": "#2b2a2a",
        "secondary": "#c8c6c5",
        "surface-container": "#201f1f",
        "surface-variant": "#353434",
        "surface-bright": "#3a3939",
        "surface-tint": "#c9c6c5",
        "surface": "#141313",
        "on-secondary-fixed-variant": "#474746",
        "tertiary": "#adc7ff",
        "on-tertiary-container": "#0075f3",
        "on-secondary-fixed": "#1c1b1b",
        "on-background": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "on-error-container": "#ffdad6",
        "primary": "#c9c6c5",
        "on-primary-fixed-variant": "#474646",
        "primary-fixed-dim": "#c9c6c5",
        "secondary-fixed": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "tertiary-fixed": "#d8e2ff",
        "outline-variant": "#444748",
        "on-surface-variant": "#c4c7c7",
        "on-secondary": "#313030",
        "surface-container-highest": "#353434",
        "secondary-fixed-dim": "#c8c6c5",
        "inverse-on-surface": "#313030",
        "on-primary-fixed": "#1c1b1b",
        "inverse-surface": "#e5e2e1",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#001a41"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        "unit": "8px",
        "gutter": "24px"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Space Grotesk', 'sans-serif'],
        technical: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}


